# Generated by Django 3.2.3 on 2021-12-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Personal Address'), (2, 'Business Address'), (3, 'Shipping Address'), (4, 'Billing Address')], default=1)),
                ('line1', models.TextField()),
                ('line2', models.TextField()),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=255)),
                ('swift_code', models.CharField(max_length=255)),
                ('ifsc_code', models.CharField(max_length=255)),
            ],
        ),
    ]
