# Generated by Django 3.2.3 on 2022-01-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.IntegerField(choices=[(1, 'Personal Address'), (2, 'Business Address'), (3, 'Shipping Address'), (4, 'Billing Address'), (5, 'Installation Address')], default=1),
        ),
    ]
