# Generated by Django 3.2.3 on 2022-07-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0005_cointransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='line2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
