# Generated by Django 3.2.3 on 2021-12-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('blog', 'Blog'), ('seminar', 'Seminar'), ('news_letter', 'News Letter')], max_length=12)),
                ('content', models.TextField()),
                ('slug', models.SlugField(blank=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['slug'], name='posts_post_slug_59b922_idx'),
        ),
    ]
