# Generated by Django 3.2.3 on 2022-01-11 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220110_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interior_decorator',
            old_name='refferal_code',
            new_name='referral_code',
        ),
    ]
