# Generated by Django 3.2.3 on 2022-01-12 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_refferal_code_interior_decorator_referral_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interior_decorator',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='interior_decorator',
            name='reffered_by',
        ),
    ]
