# Generated by Django 3.2.3 on 2022-01-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220112_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='earnings',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='interior_decorator',
            name='coins',
            field=models.IntegerField(default=0),
        ),
    ]
