# Generated by Django 3.2.3 on 2022-01-19 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220117_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interior_decorator',
            name='firm',
        ),
    ]
