# Generated by Django 3.2.3 on 2022-01-19 11:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_interior_decorator_firm'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='members',
            field=models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
