# Generated by Django 3.2.3 on 2022-01-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_firm_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='interior_decorator',
            name='reward_points',
            field=models.IntegerField(default=0),
        ),
    ]
