# Generated by Django 3.2.3 on 2021-12-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
