# Generated by Django 3.2.3 on 2021-12-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_collection_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
