# Generated by Django 3.2.3 on 2021-12-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_collection_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='tag',
            field=models.ManyToManyField(blank=True, to='product.CollectionTag'),
        ),
    ]
