# Generated by Django 3.2.3 on 2021-12-22 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_collection_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='updated_on',
        ),
    ]
