# Generated by Django 3.2.3 on 2021-12-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_collection_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
