# Generated by Django 3.2.3 on 2022-01-09 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_collection_last_updated'),
        ('product', '0009_collection_updated_on'),
    ]

    operations = [
    ]
