# Generated by Django 3.2.3 on 2022-01-14 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_merge_20220109_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='last_updated',
        ),
    ]
