# Generated by Django 3.2.3 on 2022-01-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_collection_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='pricing_category',
            field=models.CharField(choices=[('category-1', 'Wallpapers, Wall & Furniture Decals, Glass Films'), ('category-2', 'Curtains'), ('category-3', 'Frames')], default='category-1', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_2',
            field=models.IntegerField(default=0),
        ),
    ]
