# Generated by Django 3.2.3 on 2022-05-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20220529_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
