# Generated by Django 3.2.3 on 2022-04-08 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('understand_wallrus_business_ecosystem', 'Understand The Wallrus Business Ecosystem'), ('artists_agreements', 'Artist’s Agreements'), ('uploading_managing_designs', 'Uploading and Managing your Designs'), ('understanding_media_art_working', 'Understanding the Media & Art working'), ('footer', 'Footer')], max_length=50)),
                ('header', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.IntegerField()),
                ('heading', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.section')),
            ],
        ),
    ]
