# Generated by Django 3.2.3 on 2022-05-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_section_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admin_mail', 'Admin notification email')], max_length=50, unique=True)),
                ('value', models.CharField(max_length=300)),
            ],
        ),
    ]
