# Generated by Django 3.2.3 on 2021-12-10 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadowndesign',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.application'),
        ),
        migrations.AddField(
            model_name='uploadowndesign',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddIndex(
            model_name='designtag',
            index=models.Index(fields=['name'], name='designs_des_name_fa1665_idx'),
        ),
        migrations.AddField(
            model_name='design',
            name='applications',
            field=models.ManyToManyField(to='product.Application'),
        ),
    ]
