# Generated by Django 3.2.3 on 2021-12-10 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
        ('designs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='design',
            name='tags',
            field=models.ManyToManyField(to='designs.DesignTag'),
        ),
        migrations.AddField(
            model_name='customization',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.application'),
        ),
        migrations.AddField(
            model_name='customization',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='colorway',
            name='color_tags',
            field=models.ManyToManyField(limit_choices_to={'label': 'Color'}, to='designs.DesignTag'),
        ),
        migrations.AddField(
            model_name='colorway',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designs.design'),
        ),
        migrations.AddIndex(
            model_name='design',
            index=models.Index(fields=['slug'], name='designs_des_slug_74d3bd_idx'),
        ),
    ]
