# Generated by Django 3.2.3 on 2022-01-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
