# Generated by Django 3.2.3 on 2022-06-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0005_designtag_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorway',
            name='color_tags',
            field=models.ManyToManyField(blank=True, limit_choices_to={'label': 'Color'}, null=True, to='designs.DesignTag'),
        ),
    ]
