# Generated by Django 3.2.3 on 2022-06-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0006_alter_colorway_color_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designtag',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
