# Generated by Django 3.2.3 on 2022-01-12 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0002_auto_20220112_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invite',
            old_name='reffered_by',
            new_name='referred_by',
        ),
    ]
