# Generated by Django 3.2.3 on 2022-02-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissiongroup',
            name='min_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commissiongroup',
            name='min_revenue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='royaltygroup',
            name='min_design',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='royaltygroup',
            name='min_revenue',
            field=models.IntegerField(default=0),
        ),
    ]
