# Generated by Django 3.2.3 on 2022-01-19 14:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0003_alter_address_type'),
        ('orders', '0005_purchaserequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaserequest',
            old_name='user',
            new_name='decorator',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='item',
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='billing_address',
            field=models.ForeignKey(limit_choices_to={'type': 4}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_address_request', to='user_details.address'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='items',
            field=models.ManyToManyField(to='orders.Item'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='shipping_address',
            field=models.ForeignKey(limit_choices_to={'type': 3}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address_request', to='user_details.address'),
        ),
    ]
