# Generated by Django 3.2.3 on 2022-01-18 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cart',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='orders.cart'),
            preserve_default=False,
        ),
    ]
