# Generated by Django 3.2.3 on 2022-01-21 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20220119_1417'),
        ('orders', '0007_alter_cart_user'),
    ]

    operations = [
    ]
