# Generated by Django 3.2.3 on 2022-01-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_merge_0006_auto_20220119_1417_0007_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementrequest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
