# Generated by Django 3.2.3 on 2022-01-25 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20220124_1319'),
        ('orders', '0009_measurementrequest_is_approved'),
    ]

    operations = [
    ]
