# Generated by Django 3.2.3 on 2022-01-31 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0004_alter_address_type'),
        ('orders', '0012_clientcart_clientdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_details.address'),
        ),
    ]
