# Generated by Django 3.2.3 on 2022-01-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0004_alter_address_type'),
        ('orders', '0013_clientdetails_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdetails',
            name='address',
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='address',
            field=models.ManyToManyField(to='user_details.Address'),
        ),
    ]
