# Generated by Django 3.2.3 on 2022-05-30 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20220529_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='material',
        ),
    ]
