# Generated by Django 3.2.3 on 2022-05-30 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_material_is_active'),
        ('orders', '0018_remove_item_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.material'),
        ),
    ]
