# Generated by Django 3.2.3 on 2022-07-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_item_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementrequest',
            name='line2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurementrequest',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurementrequest',
            name='site_image1',
            field=models.ImageField(blank=True, null=True, upload_to='site_image/'),
        ),
    ]
