# Generated by Django 3.2.3 on 2022-07-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20220701_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='height',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='width',
            field=models.CharField(max_length=20),
        ),
    ]
