# Generated by Django 3.2.3 on 2021-12-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_frequency', models.IntegerField(choices=[(1, 'Immediately'), (2, 'Daily'), (3, 'Weekly'), (4, 'Monthly')], default=1)),
                ('payment_frequency', models.IntegerField(choices=[(1, 'Immediately'), (2, 'Daily'), (3, 'Weekly'), (4, 'Monthly')], default=1)),
                ('design_view_frequency', models.IntegerField(choices=[(1, 'Immediately'), (2, 'Daily'), (3, 'Weekly'), (4, 'Monthly')], default=1)),
                ('design_favorite_frequency', models.IntegerField(choices=[(1, 'Immediately'), (2, 'Daily'), (3, 'Weekly'), (4, 'Monthly')], default=1)),
                ('design_purchase_frequency', models.IntegerField(choices=[(1, 'Immediately'), (2, 'Daily'), (3, 'Weekly'), (4, 'Monthly')], default=1)),
            ],
            options={
                'verbose_name_plural': 'Artist notification settings',
            },
        ),
        migrations.CreateModel(
            name='InteriorDecoratorNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_commision_update_frequency', models.IntegerField(choices=[(1, 'Immediately'), (2, 'Daily'), (3, 'Weekly'), (4, 'Monthly')], default=1)),
                ('followed_artist_new_design_update_frequency', models.IntegerField(choices=[(1, 'Immediately'), (2, 'Daily'), (3, 'Weekly'), (4, 'Monthly')], default=1)),
                ('order_status_frequency', models.IntegerField(choices=[(1, 'Immediately'), (2, 'Daily'), (3, 'Weekly'), (4, 'Monthly')], default=1)),
                ('new_artist_joined_frequency', models.IntegerField(choices=[(1, 'Immediately'), (2, 'Daily'), (3, 'Weekly'), (4, 'Monthly')], default=1)),
                ('blog_news_event_notification_frequency', models.IntegerField(choices=[(1, 'Immediately'), (2, 'Daily'), (3, 'Weekly'), (4, 'Monthly')], default=1)),
            ],
            options={
                'verbose_name_plural': 'Interior Decorator notification settings',
            },
        ),
    ]
