# Generated by Django 3.2.3 on 2022-02-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_usernotifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotifications',
            name='notification_type',
            field=models.CharField(choices=[('order', 'Order'), ('follower', 'Follower'), ('product', 'product'), ('order-request', 'Order Request'), ('payment', 'Payment'), ('reward-point', 'Reward Points'), ('purchase-request', 'Purchase Request')], max_length=30),
        ),
    ]
