# Generated by Django 3.2.3 on 2022-02-05 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0005_alter_usernotifications_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotifications',
            name='notification_type',
            field=models.CharField(choices=[('order', 'Order'), ('follower', 'Follower'), ('product', 'product'), ('order-request', 'Order Request'), ('payment', 'Payment'), ('reward-point', 'Reward Points'), ('purchase-request', 'Purchase Request'), ('favourite', 'Favourite'), ('purchase_commision_update', 'purchase_commision_update'), ('followed_artist_new_design_update', 'followed_artist_new_design_update'), ('order_status', 'order_status'), ('new_artist_joined', 'new_artist_joined'), ('blog_news_event_notification', 'blog_news_event_notification'), ('design_view', 'design_view'), ('design_favorite', 'design_favorite')], max_length=50),
        ),
        migrations.CreateModel(
            name='EmailNotificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order', 'Order'), ('follower', 'Follower'), ('product', 'product'), ('order-request', 'Order Request'), ('payment', 'Payment'), ('reward-point', 'Reward Points'), ('purchase-request', 'Purchase Request'), ('favourite', 'Favourite'), ('purchase_commision_update', 'purchase_commision_update'), ('followed_artist_new_design_update', 'followed_artist_new_design_update'), ('order_status', 'order_status'), ('new_artist_joined', 'new_artist_joined'), ('blog_news_event_notification', 'blog_news_event_notification'), ('design_view', 'design_view'), ('design_favorite', 'design_favorite')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
